name: persistencia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  xml: ^6.5.0
  sqflite: ^2.4.1
  path: ^1.8.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3  # Mantén solo esta dependencia

flutter:
  uses-material-design: true
  assets:
    - assets/logoapp.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoapp.png"
  icon_size: 200
   